テーブルの作成
yushi0620honda/ToDoApp pull request #1
Opened 2022-10-01 13:39 UTC by yushi0620honda

2022-10-12 15:04 UTC, ShizukaKurosawa requested changes

2022-10-12 15:04 UTC, ShizukaKurosawa commented on src/main/resources/data.sql
> +VALUES(4, 'カレー粉', 'false', '2022-10-01');
`INSERT INTO todo_details (id, title, is_done, time_limit)`は、一番最初に記載しておけば大丈夫です。
複数行を`insert`する場合について、調べて実装し直してみてください。
一点実装とは別で気になったので記載しますが、`TODO`アプリなので「ジャガイモ」などではなく、「ジャガイモを買う」といったような動作に関する`title`が良いと思います。

2022-10-14 22:36 UTC, yushi0620honda commented on src/main/resources/data.sql
> +VALUES(4, 'カレー粉', 'false', '2022-10-01');
承知いたしました。
ありがとうございます。

2022-10-15 01:29 UTC, ShizukaKurosawa approved these changes

2022-10-15 01:29 UTC, merged