todoList.html.cssの作成
yushi0620honda/ToDoApp pull request #3
Opened 2022-10-01 16:44 UTC by yushi0620honda

2022-10-16 15:55 UTC, ShizukaKurosawa commented
画面レイアウトについて、設計書のように実装してみてください。
参考：https://docs.google.com/spreadsheets/d/1pV4kNQYP5JpVKnVyy-cS5QMWfJLjeqI-/edit#gid=1971987306

- 項目「タイトル」と「期日」について、左寄せになるようにしてください。
- 「タイトル」については、一行で表示されるようにしてください。

2022-10-16 16:01 UTC, ShizukaKurosawa requested changes

2022-10-17 10:10 UTC, kankanSunaga commented on src/main/resources/templates/html/todoList.html
> +					<!-- 動的URL --> <a th:href="@{'//' + ${}}">詳細</a>
直さなくても良いです。

コードをみればわかるコメントは記載しなくて大丈夫です。
あとこのような時は同じ行に書くのではなく
```
<!-- ↓動的URL --> 
<a th:href="@{'//' + ${}}">詳細</a>
```
などで２行に書いた方が頭が揃って綺麗に見えます。

2022-10-17 10:10 UTC, kankanSunaga approved these changes

2022-10-17 12:14 UTC, yushi0620honda commented on src/main/resources/templates/html/todoList.html
> +					<!-- 動的URL --> <a th:href="@{'//' + ${}}">詳細</a>
承知いたしました。
ありがとうございます。

2022-10-23 21:38 UTC, merged