Sprint/todo detailの作成
yushi0620honda/ToDoApp pull request #7
Opened 2022-10-05 15:06 UTC by yushi0620honda

2022-10-16 18:08 UTC, ShizukaKurosawa commented
- 「完了フラグ」のみ更新したい場合、「タイトル」と「期日」をもう一度入力する仕様はなかなかないと思うので、「タイトル」と「期日」については、デフォルトで値が入力されるようにしてください。（登録された内容が表示されるのでは、値が入力されること）
- 設計書の「処理結果」と内容が乖離しているので、設計書に記載の内容に修正してください。

2022-10-16 18:15 UTC, ShizukaKurosawa requested changes

2022-10-16 18:15 UTC, ShizukaKurosawa commented on src/main/resources/schema.sql
> +	time_limit DATE NOT NULL
設計書を　参考に修正してください。
参考：https://docs.google.com/spreadsheets/d/1paS4mXnt98ttT4742wd4sXovF0dgbYTY/edit#gid=1898107735&range=7:9

2022-10-16 18:15 UTC, ShizukaKurosawa commented on src/main/resources/static/css/completeTodoDetail.css
> +}
設計書上、このCSSは不要です。

2022-10-16 18:15 UTC, ShizukaKurosawa commented on src/main/resources/templates/html/completeTodoDetail.html
> +</html>
設計書上、このHTMLは不要です。

2022-10-19 11:20 UTC, kankanSunaga commented on pom.xml
> +		<version>2.6.5</version>
このバージョンはなぜ変わっていますか？

2022-10-19 12:46 UTC, yushi0620honda commented on pom.xml
> +		<version>2.6.5</version>
2.7.4 だと todo_details テーブルの id IDENTITY(1,1) が使用できなかったが 2.6.5 にしたところしようできるようなったため変更しました。

2022-10-21 10:42 UTC, kankanSunaga commented on pom.xml
> +		<version>2.6.5</version>
ごめんよ遅くなって。
基本的にバーションをあげることはしない方が良いとされています。
なぜかとうとバージョンアップをすると今までできていた動きができなくなり
それに合わせた修正等が必要になる場合もあります。

基本的にライブラリ特にフレームワークのバージョンは途中から変えることは非常にめんどくさいと覚えておいてください。

他の部分が今まで通り正常に動くことを証明できるならこのやり方でもいいです。

2022-10-21 13:36 UTC, yushi0620honda commented on pom.xml
> +		<version>2.6.5</version>
どんなエラーが出ていたかは忘れたのですが、日報の報告の時にspringframeworkのバージョンをダウングレードしたらIDENTITYが無事に動作したことを話しました。黒澤さんからはバージョンが要因であると言われたのでそのままTodoアプリの実装を進めました。

2022-10-22 02:10 UTC, kankanSunaga commented on pom.xml
> +		<version>2.6.5</version>
黒澤さんの意思があるならそこは尊重するので、
このままで行きましう。

ただし、フレームワークのバージョンを簡単に変えてはならないことは忘れずに。
どうしても、変えたい場合は相談です。

2022-10-23 21:38 UTC, merged