todo add formの作成
yushi0620honda/ToDoApp pull request #8
Opened 2022-10-06 16:54 UTC by yushi0620honda

2022-10-16 17:54 UTC, ShizukaKurosawa commented
設計書の「処理結果」と実装に乖離があるので、設計書を見て修正してください。
参考：https://docs.google.com/spreadsheets/d/1ZZpG6V-2t5eOdluPiw4T4-GvwPSO9cLI/edit#gid=1971987306&range=60:60

2022-10-16 17:54 UTC, ShizukaKurosawa requested changes

2022-10-16 17:54 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/todoApp/domain/repository/jdbc/UserDaoJdbc.java
> +		jdbc.update("INSERT INTO todo_details ( title, is_done, time_limit) VALUES ( ?, ?, ?)", userForm.getTitle(),
記載方法ですが、
`jdbc.update("INSERT INTO todo_details(title, is_done, time_limit) VALUES(?, ?, ?)",`
で大丈夫です。
書き方は好みなので、修正するか否かは任せます。

2022-10-16 17:54 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/todoApp/domain/repository/jdbc/UserDaoJdbc.java
> +		jdbc.update("INSERT INTO todo_details ( title, is_done, time_limit) VALUES ( ?, ?, ?)", userForm.getTitle(),
73行目と同様です。

2022-10-17 10:16 UTC, kankanSunaga commented on src/main/java/com/example/demo/todoApp/controller/CompleteTodoAddFormController.java
> -package com.example.demo.todoApp.controller;
大量のファイルが削除されているけどこれはなぜですか？

2022-10-17 10:18 UTC, kankanSunaga reviewed
なんかすんごいファイル消されてますけどこれはなぜですか？
動作確認は取れてますか？

2022-10-17 11:26 UTC, yushi0620honda commented
> なんかすんごいファイル消されてますけどこれはなぜですか？ 動作確認は取れてますか？

設計書上、不要であったため削除しました。
動作確認済みです。

2022-10-23 21:38 UTC, merged